### ISSUE TITLE
Lame dismissal of mac and linux users

### ISSUE THREAD

**Issue by edwardbair** [DozierJeff/RasterReprojection#1]
https://github.com/DozierJeff/RasterReprojection/blob/e64b059dded3d046bf6e59ff29f76dfff1b400a3/util/RasterReprojectionMemoryCheck.m#L22

The following will accomplish an equivalent memory check (in GB) on linux:

[r,w] = unix('free -g');
stats=str2double(regexp(w,'\d{1,}','match'));
availablePhysicalMemory = stats(3) + stats(6);
availableVirtualMemory = availablePhysicalMemory + stats(9);

On a mac, also in GB:

[r,w]=system('vm_stat');
stats=str2double(regexp(w,'\d{1,}','match'));
%(pages active + pages speculative + pages wired down + pages occupied by
%compressor) * page size * bytes/GB
used =  sum(stats([3 5 7 17]))*stats(1)*1e-9;
[r,w]=system('sysctl hw.memsize');
stats=regexp(w,'\d{1,}','match');
availablePhysicalMemory=str2double(stats)*1e-9-used;
[r,w]=system('sysctl vm.swapusage');
stats=regexp(w,'M','split');
availableVirtualMemory=str2double(stats{3}(10:end))*1e-3;

**Comment by DozierJeff** [comment]
Thanks! I'll add those.

From: Ned Bair ***@***.***>
Sent: Wednesday, July 7, 2021 13:37
To: DozierJeff/RasterReprojection ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [DozierJeff/RasterReprojection] Lame dismissal of mac and linux users (#1)


https://github.com/DozierJeff/RasterReprojection/blob/e64b059dded3d046bf6e59ff29f76dfff1b400a3/util/RasterReprojectionMemoryCheck.m#L22<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FDozierJeff%2FRasterReprojection%2Fblob%2Fe64b059dded3d046bf6e59ff29f76dfff1b400a3%2Futil%2FRasterReprojectionMemoryCheck.m%23L22&data=04%7C01%7C%7C394ffbc51c6b43beb97408d94187006a%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637612870356671866%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=uVEZHpqMAO5JqTHoMJ3oCqu0iF6NPcPIho5xZKujdTo%3D&reserved=0>

The following will accomplish an equivalent memory check (in GB) on linux:

[r,w] = unix('free -g');
stats=str2double(regexp(w,'\d{1,}','match'));
availablePhysicalMemory = stats(3) + stats(6);
availableVirtualMemory = availablePhysicalMemory + stats(9);

On a mac, also in GB:

[r,w]=system('vm_stat');
stats=str2double(regexp(w,'\d{1,}','match'));
%(pages active + pages speculative + pages wired down + pages occupied by
%compressor) * page size * bytes/GB
used = sum(stats([3 5 7 17]))*stats(1)*1e-9;
[r,w]=system('sysctl hw.memsize');
stats=regexp(w,'\d{1,}','match');
availablePhysicalMemory=str2double(stats)*1e-9-used;
[r,w]=system('sysctl vm.swapusage');
stats=regexp(w,'M','split');
availableVirtualMemory=str2double(stats{3}(10:end))*1e-3;

-

**Comment by DozierJeff** [comment]
fixed sometime ago
